services:
  - type: web
    name: nighttube-backend
    env: node
    plan: free
    branch: main
    root: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: FRONTEND_URL
        value: "https://andrewwe98.github.io/nighttube"
      - key: YOUTUBE_API_KEY
        value: "AIzaSyDFQCMrYouQ4ahbM7pJRGu3Hzm1QF6g_tY"
      - key: JWT_SECRET
        value: "token123"
      - key: PORT
        value: "4000"
